# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: apache-app
#   description: An example of a Backstage application.
#   annotations:
#     argocd/app-name: apache-app
#     backstage.io/kubernetes-id: my-app
#   type: service
#   owner: user:guest  
#   lifecycle: production

# ---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-demo
  description: An example of a Backstage application.
  annotations:
    argocd/app-name: my-app
    argocd/url: "https://localhost:8080/api/v1/"
    backstage.io/kubernetes-id: argocd-demo
    kubernetes.io/cluster-name: docker-desktop
spec:
  type: service
  owner: user:guest  
  lifecycle: production

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app
  description: An example of a Backstage application.
  annotations:
    argocd/app-name: my-app
    argocd/url: "https://localhost:8080/api/v1/"
    backstage.io/kubernetes-id: my-app
    kubernetes.io/cluster-name: docker-desktop    
spec:
  type: service
  owner: user:guest  
  lifecycle: production
