apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: default
  labels:
    app: apache-app
    backstage.io/kubernetes-id: apache-app
spec:
  selector:
    app: apache-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

